version: '3.9'

services:
  nextjs:
    container_name: next-13-docker-pages-auth0-prod
    build: .
    ports:
      - 3006:3001
    volumes:
      - .:/app
    environment:
      BACKEND_URL: http://meal-api:8080
    entrypoint: /bin/sh -c "npm install && npm run build && npm run start"
    networks:
    - meal-network1

networks:
  meal-network1: