version: '3.9'

services:
  nextjs:
    container_name: next-13-docker-pages-auth0
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run dev"

  nextjs-prod:
    container_name: next-13-docker-pages-auth0-prod
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run build && npm run start"