version: "3.9"

services:
  nextjs:
    container_name: next-13-docker-pages-auth0-prod
    image: flopiti/memeals-web:latest
    ports:
      - 3006:3006
    environment:
      BACKEND_URL: http://springboot:8080
    networks:
      - memealsapi_meal-network1

networks:
  memealsapi_meal-network1:
    external: true
