version: "3.9"

services:
  meal-app:
    container_name: meal-app
    build: .
    ports:
      - 3006:3006
    volumes:
      - .:/app
    environment:
      BACKEND_URL: http://fixmefood.com:8080
    entrypoint: /bin/sh -c "npm install && npm run dev"
    networks:
      - meal-network

networks:
  meal-network:
