version: '3.9'

services:
  meal-app:
    container_name: meal-app
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    environment:
      BACKEND_URL: http://mock-api:3000
    entrypoint: /bin/sh -c "npm install && npm run dev"
    networks:
    - meal-network

  mock-api:
    container_name: mock-meals
    build: .
    volumes:
      - ./:/app
    entrypoint: /bin/sh -c "npm install && npm run mock"
    ports:
      - 3000:3000
    networks:
      - meal-network

networks:
  meal-network: