//make a baseLayout component

import React from "react";
import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Head from "next/head";

const BaseLayout = ({ children } : any) => {
    return (
        <>
        <Head>
            <title>Meal App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>{children}</main>
        </>
    );
    };

export default BaseLayout;