import Head from 'next/head'
import Calendar from '@/components/Calendar'
import { useEffect, useState } from 'react'
import { useScheduledMeals } from '@/hooks/useScheduledMeals'
import { useMeals } from '@/hooks/useMeals'
import { Meal } from '@/components/ScheduledMeal'
import { GetServerSidePropsContext } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { withPageAuthRequired } from '@auth0/nextjs-auth0'
import LikedMealsList from '@/components/LikedMealsList'
import { Meals } from '@/components/Meals'
import IngredientList from '@/components/IngredientList'
import { useIngredients } from '@/hooks/useIngredients'

export default function Home() {

  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    if (window.innerWidth < 768) {
      setIsMobile(true);
    }
  }, []);

  const { getScheduledMeals } = useScheduledMeals();
  const { getMeals, getMealsLike, likeMeal, unlikeMeal } = useMeals();
  const {getIngredients,getIngredient, createIngredient } = useIngredients();
  const[scheduledMeals, setScheduledMeals] = useState<ScheduledMeal[]>([]);
  const[meals, setMeals] = useState<Meal[]>([]);
  const[likedMeals, setLikedMeals] = useState<Meal[]>([]);
  const[ingredients, setIngredients] = useState<Meal[]>([]);

  const scheduleMeal = async ({id, date, mealType,mealId, mealName, iconUrl, meal2Name, icon2Url }: ScheduledMeal) => {
    setScheduledMeals([...scheduledMeals, {id, date, mealType,mealId, mealName, iconUrl, meal2Name, icon2Url }])
  }
  const removeMeal = async (id:number) => {
    setScheduledMeals(scheduledMeals.filter((meal:any) => meal.id !== id))
  }
  const addMealToScheduledMeal = async ({id, date, mealType, mealId, mealName, iconUrl, meal2Name, icon2Url}: ScheduledMeal) => {
    setScheduledMeals([...scheduledMeals.filter((meal:any) => meal.date !== date || meal.mealType !== mealType || meal.mealName !== mealName), {id, date, mealType, mealId, mealName, iconUrl, meal2Name, icon2Url } ])
  }
  const addMeal = async (meal:Meal) => {
    setMeals([...meals, meal])
  }

  
  useEffect(() => {
    getMealsLike().then((data:any) => setLikedMeals(data))
    getMeals().then((data:any) => setMeals(data))
    getScheduledMeals().then((data:any) =>  setScheduledMeals(data));
    getIngredients().then((data:any) =>  setIngredients(data));
  }, [])  

  return (
    <>
      <Head>
        <title>MeMeals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/memeals.png" />
      </Head>

      {
        isMobile ?
        <div style={{width: '100%', display: 'inline-block'}}>
          <a href="/api/auth/logout">Logout</a>
          <Calendar scheduledMeals={scheduledMeals} scheduleMeal={scheduleMeal} removeMeal={removeMeal} addMealToScheduledMeal={addMealToScheduledMeal}/>
        </div>
        :
        <>
          <div style={{width: '80%', display: 'inline-block'}}>
            <a href="/api/auth/logout">Logout</a>
            <Calendar scheduledMeals={scheduledMeals} scheduleMeal={scheduleMeal} removeMeal={removeMeal} addMealToScheduledMeal={addMealToScheduledMeal}/>
          </div>
          <div style={{width: '15%', display: 'inline-block'}} >
            <Meals likedMeals={likedMeals} meals={meals} likeMeal={likeMeal} unlikeMeal={unlikeMeal} setLikedMeals={setLikedMeals} addMeal={addMeal}/>
          </div>
        </>
      }
      <div>
        <LikedMealsList meals={likedMeals} />
        <IngredientList ingredients={ingredients} />
      </div>

    </>
  )
}

export type ScheduledMeal = {
  id: number;
  date: string;
  mealType: string;
  mealId: number;
  mealName: string;
  iconUrl: string;
  meal2Name: string;
  icon2Url: string;
}

export const getServerSideProps = withPageAuthRequired({
  getServerSideProps: async ({ locale }: GetServerSidePropsContext) => {
    return {
      props: {
        ...(await serverSideTranslations(locale || 'en', ['common'])),
      },
    };
  },
});
