import Head from 'next/head'
import Calendar from '@/components/Calendar'
import MealList from '@/components/MealList'
import { useEffect, useState } from 'react'
import { useScheduledMeals } from '@/hooks/useScheduledMeals'
import { useMeals } from '@/hooks/useMeals'
import { Meal } from '@/components/ScheduledMeal'
import { GetServerSidePropsContext } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

export default function Home() {
  const { getScheduledMeals } = useScheduledMeals();
  const { getMeals } = useMeals();
  const[scheduledMeals, setScheduledMeals] = useState<ScheduledMeal[]>([]);
  const[meals, setMeals] = useState<Meal[]>([]);

  const scheduleMeal = async ({id, mealName, date, mealType, iconUrl, meal2Name, icon2Url }: ScheduledMeal) => {
    setScheduledMeals([...scheduledMeals, {id, mealName, date, mealType, iconUrl, meal2Name, icon2Url }])
  }
  const removeMeal = async ({mealName, date, mealType}: ScheduledMeal) => {
    setScheduledMeals(scheduledMeals.filter((meal:any) => meal.date !== date || meal.mealType !== mealType || meal.mealName !== mealName))
  }
  const addMealToScheduledMeal = async ({id, mealName, date, mealType, iconUrl, meal2Name, icon2Url}: ScheduledMeal) => {
    setScheduledMeals([...scheduledMeals.filter((meal:any) => meal.date !== date || meal.mealType !== mealType || meal.mealName !== mealName), {id, mealName, date, mealType, iconUrl, meal2Name, icon2Url } ])
  }
  useEffect(() => {
    getScheduledMeals().then((data:any) => {
      setScheduledMeals(data)}).then(() =>getMeals().then((data:any) => setMeals(data)));
  }, [])  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <a href="/api/auth/login">Login</a> */}
      <Calendar scheduledMeals={scheduledMeals} scheduleMeal={scheduleMeal} removeMeal={removeMeal} addMealToScheduledMeal={addMealToScheduledMeal}/>
      <MealList meals={meals} />
    </>
  )
}

export type ScheduledMeal = {
  id: number;
  mealName: string;
  date: string;
  mealType: string;
  iconUrl: string;
  meal2Name: string;
  icon2Url: string;
}

export const getServerSideProps = async ({locale,}: GetServerSidePropsContext) => {
  return {
    props: {
      ...(await serverSideTranslations(locale || 'en', ['common'])),
    },
  }
}